import os
import json

import pyzillow.pyzillow as pz
from slugify import slugify

ZILLOW_KEY = os.getenv("ZILLOW_KEY")

addresses = ["1620 Cannon Valley Dr, Northfield, MN",
             "1791 Larkspur Ct, Northfield, MN",
             "10310 295th St W, Northfield, MN",
             "700 Grundhoefer Ct, Northfield, MN",
             "801 Quie Ln, Northfield, MN",
             "2712 Oak Lawn Dr, Northfield, MN",
             "10461 Jacobs Ave, Northfield, MN",
             "1237 Hazelwood Way, Northfield, MN",
             "9027 Canby Ct, Northfield, MN",
             "2686 89th Ct W, Northfield, MN",
             "1804 Creek Ln, Northfield, MN",
             "29776 Hayes Ave, Northfield, MN",
             "1205 Hazelwood Way, Northfield, MN",
             "1704 Creek Ln, Northfield, MN",
             "1750 Patriot Rd, Northfield, MN",
             "3250 90th St E, Northfield, MN",
             "1800 Michigan Dr, Northfield, MN",
             "1512 Cannon Valley Dr, Northfield, MN",
             "1708 Michigan Dr, Northfield, MN",
             "1809 Creek Ln, Northfield, MN",
             "1226 Cannon Valley Dr, Northfield, MN",
             "10021 305th St W, Northfield, MN",
             "2740 300th St W, Northfield, MN",
             "1005 Heywood Rd, Northfield, MN",
             "3888 65th St W, Northfield, MN",
             "807 Thye Pkwy, Northfield, MN",
             "9045 Canby Ct, Northfield, MN",
             "909 Abbey Rd, Northfield, MN",
             "32414 Alexander Ct, Northfield, MN",
             "1103 Cannon Valley Dr, Northfield, MN",
             "1511 Quie Ln, Northfield, MN",
             "906 Crocus Ct, Northfield, MN",
             "32266 Canada Ave, Northfield, MN",
             "1008 Superior Dr, Northfield, MN",
             "1008 Abbey Rd, Northfield, MN",
             "2000 Michigan Dr, Northfield, MN",
             "2013 Sibley View Ln, Northfield, MN",
             "700 Turnberry Ln, Northfield, MN",
             "708 Hackerson Ct, Northfield, MN",
             "907 Saint Olaf Ave, Northfield, MN",
             "2698 89th Ct W, Northfield, MN",
             "206 2nd St E, Northfield, MN",
             "208 2nd St E, Northfield, MN",
             "32441 Holyoke Ave, Northfield, MN",
             "811 Thye Pkwy, Northfield, MN",
             "605 Maple Ct, Northfield, MN",
             "2004 Michigan Dr, Northfield, MN",
             "2009 Michigan Dr, Northfield, MN",
             "12136 Cannon City Blvd, Northfield, MN",
             "32500 Alta Ave, Northfield, MN",
             "510 College St, Northfield, MN",
             "1603 Goldenrod Ct, Northfield, MN",
             "1615 Quie Ln, Northfield, MN",
             "43 Fareway Dr, Northfield, MN",
             "8821 100th St E, Northfield, MN",
             "1661 Lonsdale Blvd E, Northfield, MN",
             "1708 Goldenrod Cir, Northfield, MN",
             "1628 Cannon Valley Dr, Northfield, MN",
             "704 Ford St, Northfield, MN",
             "1501 Cannon Valley Dr, Northfield, MN",
             "2678 87th Ct W, Northfield, MN",
             "2960 320th St W # 469, Northfield, MN",
             "816 Quie Ln, Northfield, MN",
             "2597 89th Ct W, Northfield, MN",
             "2019 Grant Dr, Northfield, MN",
             "1801 Creek Ln, Northfield, MN",
             "32265 Dahomey Ave, Northfield, MN",
             "1801 Creek Ln, Northfield, MN",
             "1705 Creek Ln, Northfield, MN",
             "701 Indigo Ln, Northfield, MN",
             "503 College St, Northfield, MN",
             "13277 Gates Ave, Northfield, MN",
             "10039 330th St W, Northfield, MN",
             "4755 Albany Ave, Northfield, MN",
             "10598 First Timberlane Dr, Northfield, MN",
             "10598 First Timberlane Dr, Northfield, MN",
             "2308 Valley Ct, Northfield, MN",
             "4755 Albany Ave, Northfield, MN",
             "780 Indigo Ln, Northfield, MN",
             "1258 Bluff St, Dundas, MN",
             "2308 Valley Ct, Northfield, MN",
             "2434 Valley Dr, Northfield, MN",
             "811 Mayflower Ct, Northfield, MN",
             "811 Mayflower Ct, Northfield, MN",
             "2434 Valley Dr, Northfield, MN",
             "2213 Greenfield Dr E, Northfield, MN",
             "2716 Oak Lawn Dr, Northfield, MN",
             "2716 Oak Lawn Dr, Northfield, MN",
             "708 Turnberry Ln, Northfield, MN",
             "708 Turnberry Ln, Northfield, MN",
             "1920 Tyler Ct, Northfield, MN",
             "4886 90th St E, Northfield, MN",
             "1920 Tyler Ct, Northfield, MN",
             "2111 320th St E, Northfield, MN",
             "1716 Goldenrod Cir, Northfield, MN",
             "1508 Cannon Valley Dr, Northfield, MN",
             "2667 Oak Lawn Dr, Northfield, MN",
             "1716 Goldenrod Cir, Northfield, MN",
             "2416 Pepper Ridge Ct, Northfield, MN",
             "308 Linden St N, Northfield, MN",
             "218 Orchard St N, Northfield, MN",
             "1516 Cannon Valley Dr, Northfield, MN",
             "218 Orchard St N, Northfield, MN",
             "308 Linden St N, Northfield, MN",
             "32489 Alexander Ct, Northfield, MN",
             "2416 Pepper Ridge Ct, Northfield, MN",
             "2385 Union Lake Trl, Northfield, MN",
             "8826 Canby Ct, Northfield, MN",
             "1744 Quie Ln, Northfield, MN",
             "218 Manitou St, Northfield, MN",
             "218 Manitou St, Northfield, MN",
             "2385 Union Lake Trl, Northfield, MN",
             "1217 Sumac Ln, Northfield, MN",
             "1012 Prairie Cir, Northfield, MN",
             "1012 Prairie Cir, Northfield, MN",
             "1217 Sumac Ln, Northfield, MN",
             "8826 Canby Ct, Northfield, MN",
             "913 Superior Dr, Northfield, MN",
             "6025 115th St E, Northfield, MN",
             "907 Saint Olaf Ave, Northfield, MN",
             "915 2nd St W, Northfield, MN",
             "813 Superior Dr, Northfield, MN",
             "1118 Bluff St, Dundas, MN",
             "2595 86th Ct W, Northfield, MN",
             "1145 Woodland Trl, Northfield, MN",
             "807 Saint Olaf Ave, Northfield, MN",
             "1503 Goldenrod Ct, Northfield, MN",
             "7375 115th St E, Northfield, MN",
             "401 College St, Northfield, MN",
             "816 Superior Dr, Northfield, MN",
             "3061 North Ave, Northfield, MN",
             "206 Winona St, Northfield, MN",
             "1813 Michigan Dr, Northfield, MN",
             "1605 Mayflower Dr, Northfield, MN",
             "1605 Mayflower Dr, Northfield, MN",
             "2105 Michigan Dr, Northfield, MN",
             "312 Afton Dr, Northfield, MN",
             "30700 Northfield Blvd, Northfield, MN",
             "10800 James Trl, Northfield, MN",
             "1708 Eastridge Ct, Northfield, MN",
             "606 Thye Ct, Northfield, MN",
             "11370 113th St E, Northfield, MN",
             "833 Heywood Rd, Northfield, MN",
             "1712 Goldenrod Cir, Northfield, MN",
             "709 Carter Dr, Northfield, MN",
             "13940 Ibson Ave, Nerstrand, MN",
             "649 Indigo Ln, Northfield, MN",
             "2013 Sibley View Ln, Northfield, MN",
             "1612 Cannon Valley Dr, Northfield, MN",
             "2109 Taylor Ct, Northfield, MN",
             "29420 Burma Ave, Northfield, MN",
             "804 Mayflower Ct, Northfield, MN",
             "11254 113th St E, Northfield, MN",
             "1227 Cannon Valley Dr, Northfield, MN",
             "2839 Oak Lawn Dr, Northfield, MN",
             "10800 James Trl, Northfield, MN",
             "2800 90th St E, Northfield, MN",
             "5590 Endwood Trl, Northfield, MN",
             "707 Saint Olaf Ave, Northfield, MN",
             "485 Rosewood Rd, Northfield, MN",
             "779 Indigo Ln, Northfield, MN",
             "8541 86th Ct E, Northfield, MN",
             "705 Carter Dr, Northfield, MN",
             "1116 Woodland Trl, Northfield, MN",
             "11262 113th St E, Northfield, MN",
             "12395 Cannon City Blvd, Northfield, MN",
             "1500 Cannon Valley Dr, Northfield, MN",
             "1401 Parmeadow Dr, Northfield, MN",
             "215 Nevada St, Northfield, MN",
             "302 Oak St, Northfield, MN",
             "702 Aldrich Dr, Northfield, MN",
             "415 Riley Dr, Northfield, MN",
             "2013 Erie Dr, Northfield, MN",
             "1808 Creek Ln, Northfield, MN",
             "1629 Cannon Valley Dr, Northfield, MN",
             "5990 110th St E, Northfield, MN",
             "2627 Oak Lawn Dr, Northfield, MN",
             "828 Ivanhoe Dr, Northfield, MN",
             "401 Rosewood Rd, Northfield, MN",
             "2215 Greenfield Dr E, Northfield, MN",
             "1000 Prairie Cir, Northfield, MN",
             "1212 Superior Dr, Northfield, MN",
             "5137 123rd St E, Northfield, MN",
             "1809 Creek Ln, Northfield, MN",
             "1005 Superior Dr, Northfield, MN",
             "1507 Goldenrod Ct, Northfield, MN",
             "1506 Creek Ln, Northfield, MN",
             "1604 Maple St, Northfield, MN"]

zillow_data = pz.ZillowWrapper(ZILLOW_KEY)
zipcode = 55057
for address in addresses:
    try:
        deep_search_response = zillow_data.get_deep_search_results(address, zipcode)
        result = pz.GetDeepSearchResults(deep_search_response)

        d = vars(result)
        fname = slugify(address)

        print fname

        del d['data']  # Element object not serializable

        with open("./data/{}".format(fname), 'w') as f:
            f.write(json.dumps(d))
    except:
        print "Error: {}".format(address)
